feat: Search for config file
getappmap/appmap-python pull request #304
Opened 2024-05-13 06:58 UTC by zermelo-wisen

Fixes #295.

2024-05-13 10:52 UTC, kgilpin commented
Can you pls describe the solution in the PR description.

2024-05-13 16:47 UTC, zermelo-wisen commented
> Can you pls describe the solution in the PR description.

Done.

2024-05-14 09:39 UTC, apotterri requested changes
A couple of minor changes to make, but I also wonder about the choice to use `os.path` instead of `pathlib`.

2024-05-14 09:39 UTC, apotterri commented on _appmap/test/test_util.py
> +    impoosible_file_name = str(uuid.uuid4()) + ".yml"
```suggestion
    impossible_file_name = str(uuid.uuid4()) + ".yml"
```

2024-05-14 09:39 UTC, apotterri commented on _appmap/utils.py
> +    file_path = os.path.join(start_dir, filename)
In general, it seems like it might be better to use `pathlib`. Was there a reason you chose `os.path` here?

2024-05-15 13:40 UTC, apotterri approved these changes

2024-05-15 13:40 UTC, merged